### ISSUE TITLE
Fixnout pozicování kotviček skrze fixní hlavičku, aby to fungovalo

### ISSUE THREAD

**Issue by janjelinek** [heureka/heureka.github.io#5]
Jako zbloudilý návštěvník přijdu na blog, například http://www.heurekadevs.cz/tagy/#jekyll a kotva mě napozicuje scroll stránky adekvátně k jejímu umístění a neuvidím přes ní nějaké srajdy, zvláště pak hlavičku a podobně nesmysly.

**Comment by Chaoticum** [comment]
Řekl bych, že už to je fixnuté a funguje správně. Testováno v Chrome a FF. Dva příklady:

- https://www.heurekadevs.cz/tagy/#react
- https://www.heurekadevs.cz/tagy/#api

ping @jirivich

**Comment by Dazix** [comment]
Jo jo, já to opravoval a zapomněl zavřít issue.
